### ISSUE TITLE
Tab-Complete in Console works but is not displayed

### ISSUE THREAD

**Issue by ghost** [Slackadays/Hajime#14]
**Describe the bug**
Tab-Completing inside console works, but the completed Text is invisible. You can't see whether the correct subcommand has been completed.

**Reproduction**
Can be reproduced on latest hajime build (compiled from source). As well as previous Builds. 

**Expected behavior**
See the full text of the tab-completed command.

**Other info**
Using latest build of paper

**Comment by Slackadays** [comment]
https://github.com/PaperMC/Paper/issues/8488
